# This is a basic workflow to help you get started with Actions
name: Run SC
on:
  schedule:
    # You need to set your schedule here
    - cron: "0 9,21 * * *"

jobs:
  pull_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # If using Python:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # If using Python:
      - name: Install dependencies
        run: pip install -r requirements.txt

      # If using Python:
      - name: Pull data
        run: python3 sc_Base.py

      # NOTE: This commits everything in the `data` directory. Make sure this matches your needs
      - name: Git commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add akaka.csv
          git commit -m "Add data for $DATE"

      # NOTE: Check that your branch name is correct here
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

